apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ledger-py.fullname" . }}-config
  labels:
    {{- include "ledger-py.labels" . | nindent 4 }}
data:
  {{- include "ledger-py.configData" . | nindent 2 }}
