apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ledger-py.fullname" . }}-secret
  labels:
    {{- include "ledger-py.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- include "ledger-py.secretData" . | nindent 2 }}
