apiVersion: v1
kind: Service
metadata:
  name: {{ include "ledger-py.fullname" . }}-api
  labels:
    {{- include "ledger-py.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "ledger-py.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
